--CREATE TABLE IF NOT EXISTS users (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     name VARCHAR(255) NOT NULL,
--     email VARCHAR(512) NOT NULL,
--     CONSTRAINT pk_users PRIMARY KEY (id),
--     CONSTRAINT uq_user_email UNIQUE (email)
-- );
--
-- CREATE TABLE IF NOT EXISTS items (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     owner_id BIGINT,
--     name VARCHAR(255) NOT NULL,
--     description VARCHAR(255) NOT NULL,
--     available BOOLEAN NOT NULL,
----     is_available BOOLEAN NOT NULL,
--     CONSTRAINT pk_items PRIMARY KEY (id),
--     CONSTRAINT fk_items_user_id FOREIGN KEY (owner_id) REFERENCES users (id)
-- );
--
-- CREATE TABLE IF NOT EXISTS bookings (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     start_date TIMESTAMP WITHOUT TIME ZONE,
--     end_date TIMESTAMP WITHOUT TIME ZONE,
--     item_id BIGINT,
--     booker_id BIGINT,
--     status VARCHAR,
--     CONSTRAINT pk_bookings PRIMARY KEY (id),
--     CONSTRAINT fk_bookings_user_id FOREIGN KEY (booker_id) REFERENCES users (id),
--     CONSTRAINT fk_bookings_item_id FOREIGN KEY (item_id) REFERENCES items (id)
-- );
--
--CREATE TABLE IF NOT EXISTS comments (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--    text VARCHAR(255),
--    item_id BIGINT,
--    author_id BIGINT,
--    CONSTRAINT pk_comments PRIMARY KEY (id),
--    CONSTRAINT fk_comments_user_id FOREIGN KEY (author_id) REFERENCES users (id),
--    CONSTRAINT fk_comments_item_id FOREIGN KEY (item_id) REFERENCES items (id)
--);
--
--CREATE TABLE IF NOT EXISTS requests (
--    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
--    description VARCHAR(512),
--    user_id BIGINT,
--    CONSTRAINT fk_requests_user_id FOREIGN KEY (user_id) REFERENCES users (id),
--    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
--);

CREATE TABLE IF NOT EXISTS users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR(255) NOT NULL,
    email  VARCHAR(512) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS requests
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(512),
    requestor_id BIGINT REFERENCES users (id),
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
    );

CREATE TABLE IF NOT EXISTS items
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    description VARCHAR(512),
    is_available BOOLEAN,
    owner_id BIGINT REFERENCES users (id),
    request_id BIGINT REFERENCES requests (id)
    );

CREATE TABLE IF NOT EXISTS bookings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date TIMESTAMP WITHOUT TIME ZONE,
    item_id BIGINT REFERENCES items (id),
    user_id BIGINT REFERENCES users (id),
    status VARCHAR(25)
    );


CREATE TABLE IF NOT EXISTS comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR(512),
    item_id BIGINT REFERENCES items (id),
    user_id BIGINT REFERENCES users (id),
    created TIMESTAMP WITHOUT TIME ZONE
    );

